# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_system_management_wiz_0_0/bd_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_system_management_wiz_0_0 || ORIG_REF_NAME==bd_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_xbar_0/bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_xbar_0 || ORIG_REF_NAME==bd_xbar_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ps8_0_axi_periph_0/bd_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_ps8_0_100M_0/bd_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_ps8_0_100M_0 || ORIG_REF_NAME==bd_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_bram_ctrl_0_0/bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_blk_mem_gen_0_0/bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_blk_mem_gen_0_0 || ORIG_REF_NAME==bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_intc_0_0/bd_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_intc_0_0 || ORIG_REF_NAME==bd_axi_intc_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_ds_0/bd_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_auto_ds_0 || ORIG_REF_NAME==bd_auto_ds_0} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_pc_0/bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_auto_pc_0 || ORIG_REF_NAME==bd_auto_pc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_ds_1/bd_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_auto_ds_1 || ORIG_REF_NAME==bd_auto_ds_1} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_ds_2/bd_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_auto_ds_2 || ORIG_REF_NAME==bd_auto_ds_2} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_pc_1/bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_auto_pc_1 || ORIG_REF_NAME==bd_auto_pc_1} -quiet] -quiet

# XDC: /home/caccolillo/Documents/cat_doorbell/Cat_Doorbell/vivado/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/bd_ooc.xdc
